version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - Shopify/platform-dev-tools-education
  ignore:
  - dependency-name: "@shopify/polaris"
    versions:
    - 5.15.0
    - 6.0.1
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.14
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
